var cav_list = 
[
	{'simpleName': "4G",'fullName':"the 4th Generation mobile communication technology",'description':"第四代移动通信技术"},
	{'simpleName': "5G",'fullName':"the 5th Generation mobile communication technology",'description':"第五代移动通信技术"},
	{'simpleName': "5GNR",'fullName':"5G New Radio",'description':"基于OFDM的全新空口设计的全球性5G标准"},
	{'simpleName': "ABS",'fullName':"Anti-lock Braking System",'description':"制动防抱死系统"},
	{'simpleName': "ACL",'fullName':"Access Control List",'description':"访问控制列表"},
	{'simpleName': "ADS",'fullName':"Application Data-Exchange Service",'description':"应用数据交换服务"},
	{'simpleName': "AID",'fullName':"Application Identification",'description':"应用标识"},
	{'simpleName': "API",'fullName':"Application Programming Interface",'description':"应用程序编程接口"},
	{'simpleName': "ASN.1",'fullName':"Abstract Syntax Notation One",'description':"抽象语法记法"},
	{'simpleName': "AVW",'fullName':"Abnormal Vehicle Warning",'description':"异常车辆提醒"},
	{'simpleName': "BSM",'fullName':"Basic Safety Message",'description':"基本安全消息"},
	{'simpleName': "BSW",'fullName':"Blind Spot Warning",'description':"盲区预警"},
	{'simpleName': "BSW-LCW",'fullName':"Blind Spot Warning-Lane Change Warning",'description':"盲区预警-变道辅助"},
	{'simpleName': "CA",'fullName':"Certification Authority",'description':"认证机构的国际通称，是指对数字证书的申请者发放、管理、取消数字证书的机构"},
	{'simpleName': "CACC",'fullName':"Cooperative Adaptive Cruise Control",'description':"协作式自适应巡航"},
	{'simpleName': "CAN",'fullName':"Controller Area Network",'description':"控制器局域网络"},
	{'simpleName': "CAV",'fullName':"Collision Avoidance Range",'description':"防撞距离"},
	{'simpleName': "CAV",'fullName':"Connected-Automated Vehicle",'description':"智能网联汽车"},
	{'simpleName': "CBR",'fullName':"Chanel Busy Ratio",'description':"信道繁忙率"},
	{'simpleName': "CDN",'fullName':"Content Distribution Network",'description':"内容分发网络"},
	{'simpleName': "CHPVP",'fullName':"Cooperative High Priority Vehicle Passing",'description':"协作式优先车辆通行"},
	{'simpleName': "CIP",'fullName':"Cooperative Intersection Passing",'description':"协作式交叉口通行"},
	{'simpleName': "C-ITS",'fullName':"China ITS Industry Alliance",'description':"中国智能交通产业联盟"},
	{'simpleName': "CLC",'fullName':"Cooperative Lane Change",'description':"协作式变道"},
	{'simpleName': "CLPMM",'fullName':"Connectionless Platooning Management Message",'description':"编队管理消息"},
	{'simpleName': "CLW",'fullName':"Control Lost Warning",'description':"车辆失控预警"},
	{'simpleName': "CPM",'fullName':"Cooperative Platooning Management",'description':"协作式车辆编队管理"},
	{'simpleName': "CSAE",'fullName':"Society of Automotive Engineers of China",'description':"中国汽车工程学会"},
	{'simpleName': "C-V2X",'fullName':"Cellular-V2X",'description':"蜂窝车联网"},
	{'simpleName': "CVM",'fullName':"Cooperative Vehicle Merge",'description':"协作式车辆汇入"},
	{'simpleName': "DDS",'fullName':"Differential Data Service",'description':"差分数据服务"},
	{'simpleName': "DE",'fullName':"Data Element",'description':"数据元素"},
	{'simpleName': "DF",'fullName':"Data Frame",'description':"数据帧"},
	{'simpleName': "DLM",'fullName':"Dynamic Lane Management",'description':"动态车道管理"},
	{'simpleName': "DME",'fullName':"DSRC Management Entity",'description':"专用短程通信管理实体"},
	{'simpleName': "DNPW",'fullName':"Do Not Pass Warning",'description':"逆向超车预警"},
	{'simpleName': "DSM",'fullName':"DSRC Short Message",'description':"专用短程通信短消息"},
	{'simpleName': "DSMP",'fullName':"Dedicated Short MessageProtocol",'description':"专用短程通信短消息协议"},
	{'simpleName': "DSRC",'fullName':"Dedicated Short Range Communications",'description':"专用短程通信"},
	{'simpleName': "DTC",'fullName':"Distance To Collision",'description':"碰撞距离"},
	{'simpleName': "DTI",'fullName':"Distance-to-Intersection",'description':"到交叉口的距离"},
	{'simpleName': "EBW",'fullName':"Emergency Brake Warning",'description':"紧急制动预警"},
	{'simpleName': "ESP",'fullName':"Electronic Stability Program",'description':"车身电子稳定系统"},
	{'simpleName': "ETC",'fullName':"Electronic Toll Collection",'description':"电子不停车收费系统"},
	{'simpleName': "ETH",'fullName':"ethernet",'description':"以太网接口"},
	{'simpleName': "ETSI",'fullName':"European Telecommunications Standards Institute",'description':"欧洲电信标准化协会"},
	{'simpleName': "EV",'fullName':"Equipped Vehicle",'description':"装载通信系统的车辆"},
	{'simpleName': "EVW",'fullName':"Emergency Vehicle Warning",'description':"紧急车辆提醒"},
	{'simpleName': "FCW",'fullName':"Forward Collision Warning",'description':"前向碰撞预警"},
	{'simpleName': "FDDLTE",'fullName':"Frequency Division Duplexing LTE",'description':"频分双工LTE"},
	{'simpleName': "GB",'fullName':"Guo Biao (Nation Standard)",'description':"中国国家标准"},
	{'simpleName': "GLOSA",'fullName':"Green Light Optimal Speed Advisory",'description':"绿波车速引导"},
	{'simpleName': "GNSS",'fullName':"Global Navigation Satellite System",'description':"全球导航卫星系统"},
	{'simpleName': "GPS",'fullName':"Global Positioning System",'description':"全球定位系统"},
	{'simpleName': "GSPA",'fullName':"Guidance Service in Parking Area",'description':"场站路径引导服务"},
	{'simpleName': "HDMI",'fullName':"High Definition Multimedia Interface",'description':"高清晰度多媒体接口"},
	{'simpleName': "HIL",'fullName':"Hardware in loop",'description':"硬件在环测试"},
	{'simpleName': "HLW",'fullName':"Hazardous Location Warning",'description':"道路危险状况预警"},
	{'simpleName': "HMI",'fullName':"Human Machine Interface",'description':"人机交互界面"},
	{'simpleName': "HSM",'fullName':"Hardware Security Module",'description':"硬件安全模块"},
	{'simpleName': "HTTPS",'fullName':"Hyper Text Transfer Protocol over Secure Layer",'description':"安全套接字层超本文传输协议"},
	{'simpleName': "HV",'fullName':"Host Vehicle",'description':"主车"},
	{'simpleName': "IA",'fullName':"Information Age",'description':"消息生存周期"},
	{'simpleName': "ICW",'fullName':"Intersection Collision Warning",'description':"交叉路口碰撞预警"},
	{'simpleName': "ID",'fullName':"Identification",'description':"标识"},
	{'simpleName': "IP",'fullName':"Internet Protocol",'description':"网际互连协议"},
	{'simpleName': "IPG",'fullName':"Inter-Packet Gap",'description':"收包间隔"},
	{'simpleName': "IPV4",'fullName':"Internet Protocol Version 4",'description':"互联网协议的第四版"},
	{'simpleName': "IPV6",'fullName':"Internet Protocol Version 6",'description':"互联网协议的第六版"},
	{'simpleName': "ISO",'fullName':"International Standards Organization",'description':"国际标准化组织"},
	{'simpleName': "ITS",'fullName':"Intelligent Transportation Systems",'description':"智能交通系统"},
	{'simpleName': "ITT",'fullName':"Inter-Transmit Time",'description':"发包间隔"},
	{'simpleName': "IVS",'fullName':"In-Vehicle Signage",'description':"车内标牌"},
	{'simpleName': "LCW",'fullName':"Lane Change Warning",'description':"变道预警"},
	{'simpleName': "LDW",'fullName':"Lane Departure Warning",'description':"车道偏离预警"},
	{'simpleName': "LED",'fullName':"Light Emitting Diode",'description':"发光二极管"},
	{'simpleName': "LTA",'fullName':"Left Turn Assistant",'description':"左转辅助"},
	{'simpleName': "LTE",'fullName':"Long Term Evolution",'description':"长期演进技术"},
	{'simpleName': "LTE-V2X",'fullName':"LTE Vehicle to Everything",'description':"基于LTE的车联网无线通信技术"},
	{'simpleName': "MAP",'fullName':"MAP",'description':"地图消息"},
	{'simpleName': "MEC",'fullName':"Moblie Edge Computing",'description':"边缘计算技术"},
	{'simpleName': "MIB",'fullName':"Management Information Base",'description':"管理信息库"},
	{'simpleName': "MIL",'fullName':"Model In Loop",'description':"模型在环测试"},
	{'simpleName': "MTBF",'fullName':"Mean Time Between Failure",'description':"平均故障间隔时间"},
	{'simpleName': "Nano SIM",'fullName':"Nano SIM卡",'description':"新一代的手机SIM卡"},
	{'simpleName': "NHTSA",'fullName':"National Highway Traffic Safety Administration",'description':"美国高速公路安全管理局"},
	{'simpleName': "NSA",'fullName':"Non－Standalone",'description':"非独立组网"},
	{'simpleName': "NTP",'fullName':"Network Time Protocol",'description':"网络时间协议"},
	{'simpleName': "NV",'fullName':"Normal Vehicle",'description':"未装载通信系统的普通车辆"},
	{'simpleName': "OBU",'fullName':"On-Board Unit",'description':"车载单元"},
	{'simpleName': "OMC",'fullName':"Operation and Maintenance Center",'description':"操作维护中心"},
	{'simpleName': "OTG",'fullName':"OTG",'description':"主要应用于不同的设备或移动设备间的联接，进行数据交换"},
	{'simpleName': "P2P",'fullName':"Point to Point",'description':"点对点"},
	{'simpleName': "PAM",'fullName':"Parking Area Map",'description':"停车场地图"},
	{'simpleName': "PAM",'fullName':"Parking Area Message",'description':"停车场地图"},
	{'simpleName': "PC5",'fullName':"PC5",'description':"使用V2X业务UE之间用户面进行D2D直接通信的接口"},
	{'simpleName': "PDC",'fullName':"Probe Data Collection",'description':"浮动车数据采集"},
	{'simpleName': "PER",'fullName':"Packet Error Ratio",'description':"丢包率"},
	{'simpleName': "PIL",'fullName':"Processor In Loop",'description':"处理器在环测试"},
	{'simpleName': "PoE",'fullName':"Power Over Ethernet",'description':"有源以太网"},
	{'simpleName': "PSE",'fullName':"Power Sourcing Equipment",'description':"供电设备"},
	{'simpleName': "PSM",'fullName':"Personal Safety Message",'description':"个体安全消息"},
	{'simpleName': "QoS",'fullName':"Quality of Service",'description':"服务质量"},
	{'simpleName': "RJ45",'fullName':"Registered Jack45",'description':"标准8位模块化接口"},
	{'simpleName': "RLVW",'fullName':"Red Light Violation Warning",'description':"闯红灯预警"},
	{'simpleName': "RS232",'fullName':"RS232",'description':"异步传输标准接口"},
	{'simpleName': "RSA",'fullName':"Road Side Alert",'description':"路侧单元发布的交通事件消息"},
	{'simpleName': "RSC",'fullName':"Road Side Coordination",'description':"路侧协调消息"},
	{'simpleName': "RSI",'fullName':"Road Side Information",'description':"路侧信息"},
	{'simpleName': "RSM",'fullName':"Road Side Message",'description':"路侧单元消息"},
	{'simpleName': "RSSI",'fullName':"Received Signal Strength Indication",'description':"接收的信号强度指示"},
	{'simpleName': "RSU",'fullName':"Road Side Unit",'description':"路侧单元"},
	{'simpleName': "RTCM",'fullName':"Radio Technical Commission for Maritime Services",'description':"国际海运事业无线电技术委员会"},
	{'simpleName': "RTK",'fullName':"Real-Time Kinematic",'description':"实时动态"},
	{'simpleName': "RTS",'fullName':"Road Tolling Service",'description':"道路收费服务"},
	{'simpleName': "RV",'fullName':"Remote Vehicle",'description':"远车"},
	{'simpleName': "SA",'fullName':"Standalone",'description':"独立组网"},
	{'simpleName': "SAE",'fullName':"Society of Automotive Engineers",'description':"美国汽车工程师学会"},
	{'simpleName': "SDK",'fullName':"Software Development Kit",'description':"软件开发工具包"},
	{'simpleName': "SDS",'fullName':"Sensor Data Sharing",'description':"感知数据共享"},
	{'simpleName': "SIL",'fullName':"Software In Loop",'description':"软件在环测试"},
	{'simpleName': "SLW",'fullName':"Speed Limit Warning",'description':"限速预警"},
	{'simpleName': "SNMP",'fullName':"Simple Network Management Protocol",'description':"简单网络管理协议"},
	{'simpleName': "SON",'fullName':"Self-Organizing Network",'description':"自组织网络"},
	{'simpleName': "SPAT",'fullName':"Signal Phase and Timing Message",'description':"信号灯相位与配时消息"},
	{'simpleName': "SPI",'fullName':"Service Provider Interface",'description':"服务提供者接口"},
	{'simpleName': "SSM",'fullName':"Sensor Sharing Message",'description':"感知共享消息"},
	{'simpleName': "SVW",'fullName':"Signal Violation Warning",'description':"闯红灯预警"},
	{'simpleName': "TC",'fullName':"Target Classification",'description':"目标分类"},
	{'simpleName': "TCP",'fullName':"Transmission Control Protocol",'description':"传输控制协议"},
	{'simpleName': "TCS",'fullName':"Traction Control System",'description':"牵引力控制系统"},
	{'simpleName': "TDDLTE",'fullName':"Time Division Duplexing LTE",'description':"时分双工LTE"},
	{'simpleName': "TE",'fullName':"Tracking Error",'description':"位置跟踪误差"},
	{'simpleName': "TEST",'fullName':"TEST",'description':"提供测试使用的私有消息格式"},
	{'simpleName': "TJW",'fullName':"Traffic Jam Warning",'description':"前方拥堵提醒"},
	{'simpleName': "TLS",'fullName':"Transport Layer Security",'description':"安全传输层协议"},
	{'simpleName': "TPM",'fullName':"Traffic Probe Message",'description':"交通信息浮动采集消息"},
	{'simpleName': "TTC",'fullName':"Time-to-Collision",'description':"碰撞预计时间"},
	{'simpleName': "TTI",'fullName':"Time-to-Intersection",'description':"到达交叉口预计时间"},
	{'simpleName': "UDP",'fullName':"User Data Protocol",'description':"用户数据报协议"},
	{'simpleName': "UPER",'fullName':"Unaligned Packet Encoding Rules",'description':"非对齐压缩编码规则"},
	{'simpleName': "UTC",'fullName':"Coordinated Universal Time",'description':"协调世界时"},
	{'simpleName': "Uu",'fullName':"User to Network interface Universal",'description':"Uu空中接口实现UE和EUTRAN的通信"},
	{'simpleName': "V2I",'fullName':"Vehicle to Infrastructure",'description':"车载单元与路侧单元通信"},
	{'simpleName': "V2P",'fullName':"Vehicle to Pedestrians",'description':"车载单元与行人设备通信"},
	{'simpleName': "V2V",'fullName':"Vehicle to Vehicle",'description':"车载单元之间通信"},
	{'simpleName': "V2X",'fullName':"Vehicle to Everything",'description':"车载单元与其他设备通信"},
	{'simpleName': "VIN",'fullName':"Vehicle ID Number",'description':"车辆识别码"},
	{'simpleName': "VIR",'fullName':"Vehicle Intention And Request",'description':"车辆意图和请求"},
	{'simpleName': "VNFP",'fullName':"Vehicle Near-Field Payment",'description':"汽车近场支付"},
	{'simpleName': "VPM",'fullName':"Vehicle Payment Message",'description':"车辆支付消息"},
	{'simpleName': "VRU",'fullName':"Vulnerable Road User",'description':"弱势交通参与者"},
	{'simpleName': "VRUCW",'fullName':"Vulnerable Road User Collision Warning",'description':"弱势交通参与者碰撞预警"},
	{'simpleName': "VRUSP",'fullName':"Vulnerable Road User Safe Passing",'description':"弱势交通参与者安全通行"},
	{'simpleName': "WEB",'fullName':"World Wide Web",'description':"全球广域网"}

]